version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "wechat-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-sz3rr8x8w1qf"
s3_prefix = "wechat-api"
region = "ap-northeast-1"
confirm_changeset = false
beta_features = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
